name: bmad-career-coach
version: 1.0.0
short-title: Career Coach Pack
description: >-
  Professional Career Coach expansion pack for BMad Method - Comprehensive career
  planning, resume building, interview preparation, and professional development
author: Your Name
slashPrefix: bmadcc
